services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  rag-app:
    build: .
    env_file: .env
    container_name: rag-app
    depends_on:
      - qdrant
    environment:
      QDRANT_URL: "http://qdrant:6333"
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  qdrant_data: